# Generated by Django 3.1.7 on 2021-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='1998-08-01', verbose_name='Date de naissance'),
            preserve_default=False,
        ),
    ]
