# Generated by Django 3.1.7 on 2021-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_student_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Numero du groupe')),
            ],
        ),
    ]
