# Generated by Django 3.1.7 on 2021-03-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default='B122', on_delete=django.db.models.deletion.PROTECT, to='grades.group'),
            preserve_default=False,
        ),
    ]
