# Generated by Django 3.1.7 on 2021-03-02 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('short_form', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Cours réduit')),
                ('wording', models.CharField(max_length=25, verbose_name='Cours')),
                ('ects', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='ECTS')),
            ],
        ),
    ]
