# Generated by Django 3.1.7 on 2021-03-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('trigram', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Abrégé')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='grades.course')),
            ],
        ),
    ]
