# Generated by Django 3.1.7 on 2021-03-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='PHA', on_delete=django.db.models.deletion.PROTECT, to='grades.teacher'),
            preserve_default=False,
        ),
    ]
