# Generated by Django 3.1.7 on 2021-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_auto_20210302_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='grades.Course'),
        ),
    ]
