# Generated by Django 3.1.7 on 2021-03-02 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteStudent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)], verbose_name='noteStudent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.student')),
            ],
        ),
    ]
